# Generated by Django 4.2.8 on 2023-12-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_board_user_grouptasks_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='gtasks',
        ),
        migrations.RemoveField(
            model_name='grouptasks',
            name='task',
        ),
        migrations.AddField(
            model_name='grouptasks',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.board'),
        ),
        migrations.AddField(
            model_name='task',
            name='group_tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.grouptasks'),
        ),
    ]
